### ISSUE TITLE
build.outDir must not be the same directory of root or a parent directory of root

### ISSUE THREAD

**Issue by hschletz** [nextcloud-libraries/nextcloud-vite-config#171]
After updateing Vite from 5.2.8 to 5.2.10, I get this warning:

> (!) build.outDir must not be the same directory of root or a parent directory of root as this could cause Vite to overwriting source files with build outputs.

According to the comment in the code, this is set on purpose.

**Comment by susnux** [comment]
Yes this is done on purpose for apps to be able to output code to `/js` while styles go into `/css` so this error can be ignored.

**Comment by hschletz** [comment]
Is there a way to suppress the message?
